version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres_server
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "3307:3307"
    volumes:
      - mari_data:/var/lib/postgres

volumes:
  mari_data: