version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3305"
    volumes:
      - mari_data:/var/lib/mysql

volumes:
  mari_data: